import { Heading } from '@chakra-ui/react'
import Head from 'next/head'
import { BlogCard } from '../components/blogCard'
import { fetchBlogPosts } from '../graphql/queries'
import { formatBlogPosts } from '../utils'

export default function Home({ blogPosts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading mb="10" textAlign="center">
          Welcome to my blog!
        </Heading>

        <BlogCard blogPosts={blogPosts} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const blogPosts = await fetchBlogPosts(
    process.env.GITHUB_USERNAME,
    process.env.GITHUB_REPO,
    process.env.GITHUB_TOKEN
  )

  const formattedBlogPosts = await formatBlogPosts(blogPosts)

  return {
    props: { blogPosts: formattedBlogPosts },
  }
}
